### ISSUE TITLE
why the results look choppy and noisy?

### ISSUE THREAD

**Issue by ethanhe42** [xmu-xiaoma666/X-Mesh#1]
Thanks for your great work and open sourcing. I'm just curious why the results look choppy and noisy.

**Comment by xmu-xiaoma666** [comment]
did you use the same hyper-parameters in script/train.sh?

**Comment by ethanhe42** [comment]
I mean there're some white dots or noise from the results on your project page.

**Comment by xmu-xiaoma666** [comment]
can you paste some images?

**Comment by ethanhe42** [comment]
you can clearly see white dots and alias. It might be a problem when you render to image. The obj looks fine

<img src="https://github.com/xmu-xiaoma666/X-Mesh/raw/master/images/Castle/img/eval.gif">

**Comment by xmu-xiaoma666** [comment]
Yes, this may be due to issues with the renderer and viewing angle. When changing the viewing angle (such as from the top), this problem does not exist.
